# Generated by Django 5.2.12 on 2026-03-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.CharField(default='Technology', max_length=100),
        ),
    ]
