# Generated by Django 5.2.12 on 2026-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_domain_tenant_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='is_customer_facing',
            field=models.BooleanField(default=False),
        ),
    ]
