# Generated by Django 5.2.12 on 2026-03-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticketnote_is_customer_facing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plan_tier',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
